name: PaperPluginTest
version: 1.0.0
main: org.atrimilan.paperplugintest.PaperPluginTest
description: A simple project to get started with Paper plugin development
author: Atrimilan
website: https://github.com/Atrimilan/PaperPluginTest
api-version: '1.21.4'