name: PaperPluginTemplate
version: 1.0.0
main: org.atrimilan.paperplugintemplate.PaperPluginTemplate
description: A simple project to get started with Paper plugin development
author: Atrimilan
website: https://github.com/Atrimilan/PaperPluginTemplate
api-version: '1.21.4'