name: Publish on GitHub and CurseForge
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build plugin with Gradle
        run: ./gradlew build

      - name: List output files
        run: ls -R ./build/libs/

      - name: Publishing plugin on GitHub and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ vars.CURSEFORGE_PROJECT_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/*.jar
          loaders: paper

      - name: End message
        run: echo 'Plugin has been successfully published ✅'